create table if not exists blog_user (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    password varchar(255) not null,
    phone_number varchar(255),
    email varchar(255),
    description varchar(255),
    user_roles varchar(255) array,
    primary key (id)
);

create table if not exists comment (
    id bigint generated by default as identity,
    comment varchar(255),
    username varchar(255),
    "photo_id" bigint,
    primary key (id)
);

create table if not exists comment (
    id bigint generated by default as identity,
    comment varchar(255),
    username varchar(255),
    "photo_id" bigint,
    primary key (id),
    foreign key ("photo_id") references photo
);

create table if not exists photo (
    id bigint generated by default as identity,
    content clob,
    description varchar(255),
    name varchar(255),
    upload_time timestamp(6),
    uploader varchar(255),
    "blog_user_id" bigint,
    primary key (id),
    foreign key ("blog_user_id") references blog_user
);

merge into blog_user key (id)
values (1, 'chris', 'chris', '75639562', 'chris@hkmu.edu', 'I am Chris', array['USER']);

merge into blog_user key (id)
values (2, 'sarah', 'sarah', '51236785', 'sarah@hkmu.edu', 'I am Sarah', array['USER']);

merge into blog_user key (id)
values (3, 'max', 'max', '64023198', 'max@hkmu.edu', 'I am Max', array['USER', 'ADMIN']);